#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-groovy
Version  : 2.4.12
Release  : 1
URL      : https://github.com/apache/groovy/archive/GROOVY_2_4_12.tar.gz
Source0  : https://github.com/apache/groovy/archive/GROOVY_2_4_12.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause EPL-1.0 Public-Domain
Requires: mvn-groovy-license = %{version}-%{release}
BuildRequires : apache-ant
BuildRequires : buildreq-mvn
BuildRequires : gradle

%description
//////////////////////////////////////////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

%package license
Summary: license components for the mvn-groovy package.
Group: Default

%description license
license components for the mvn-groovy package.


%prep
%setup -q -n groovy-GROOVY_2_4_12

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-groovy
cp licenses/LICENSE-BASE %{buildroot}/usr/share/package-licenses/mvn-groovy/licenses_LICENSE-BASE
cp licenses/LICENSE-JARJAR %{buildroot}/usr/share/package-licenses/mvn-groovy/licenses_LICENSE-JARJAR
cp licenses/hamcrest-license.txt %{buildroot}/usr/share/package-licenses/mvn-groovy/licenses_hamcrest-license.txt
cp licenses/jsr166y-license.txt %{buildroot}/usr/share/package-licenses/mvn-groovy/licenses_jsr166y-license.txt
cp licenses/junit-license.txt %{buildroot}/usr/share/package-licenses/mvn-groovy/licenses_junit-license.txt

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-groovy/licenses_LICENSE-BASE
/usr/share/package-licenses/mvn-groovy/licenses_LICENSE-JARJAR
/usr/share/package-licenses/mvn-groovy/licenses_hamcrest-license.txt
/usr/share/package-licenses/mvn-groovy/licenses_jsr166y-license.txt
/usr/share/package-licenses/mvn-groovy/licenses_junit-license.txt
